const learningContent = {
  lessons: [
    { id: 1, phase: "Phase 1", title: "あいさつと基本動詞", theme: "発音と超基本文" },
    { id: 2, phase: "Phase 1", title: "自己紹介", theme: "是 と 名前" },
    { id: 3, phase: "Phase 1", title: "疑問文", theme: "吗 と 什么" },
    { id: 4, phase: "Phase 1", title: "否定文", theme: "不 と 没" },
    { id: 5, phase: "Phase 1", title: "家族", theme: "人称代詞と的" },
    { id: 6, phase: "Phase 1", title: "時間", theme: "曜日と時刻" },
    { id: 7, phase: "Phase 1", title: "場所", theme: "在 と 去" },
    { id: 8, phase: "Phase 1", title: "買い物", theme: "量詞と値段" },
    { id: 9, phase: "Phase 2", title: "経験", theme: "过" },
    { id: 10, phase: "Phase 2", title: "完了", theme: "了" },
    { id: 11, phase: "Phase 2", title: "進行", theme: "在 と 正在" },
    { id: 12, phase: "Phase 2", title: "比較", theme: "比" },
    { id: 13, phase: "Phase 2", title: "可能", theme: "能・会・可以" },
    { id: 14, phase: "Phase 2", title: "結果補語", theme: "完・到・懂" },
    { id: 15, phase: "Phase 2", title: "方向補語", theme: "来・去" },
    { id: 16, phase: "Phase 2", title: "把構文入門", theme: "処置文" },
    { id: 17, phase: "Phase 3", title: "長めの会話", theme: "内容理解" },
    { id: 18, phase: "Phase 3", title: "日文中訳", theme: "検定式作文" },
    { id: 19, phase: "Phase 3", title: "読解語彙", theme: "接続詞" },
    { id: 20, phase: "Phase 3", title: "3級ミックス", theme: "総合演習" },
  ],
  cards: [
    { lesson: 1, type: "Vocabulary", title: "単語", hanzi: "学习", pinyin: "xuéxí", prompt: "意味を選んでください。", choices: ["勉強する", "旅行する", "休む", "買う"], answer: "勉強する", note: "毎日の学習を表す基本動詞です。" },
    { lesson: 1, type: "Vocabulary", title: "単語", hanzi: "汉语", pinyin: "Hànyǔ", prompt: "意味を選んでください。", choices: ["中国語", "日本語", "英語", "韓国語"], answer: "中国語", note: "中国語の言語名です。中国 は Zhōngguó。" },
    { lesson: 1, type: "Grammar", title: "基本語順", hanzi: "我学习汉语。", pinyin: "wǒ xuéxí Hànyǔ.", prompt: "文の意味を選んでください。", choices: ["私は中国語を勉強します", "私は中国へ行きます", "彼は中国語を話します", "私は本を読みます"], answer: "私は中国語を勉強します", note: "基本語順は 主語 + 動詞 + 目的語 です。" },
    { lesson: 1, type: "Listening", title: "聞き取り", hanzi: "你好。", pinyin: "nǐ hǎo.", prompt: "音声を聞いて意味を選んでください。", choices: ["こんにちは", "ありがとう", "さようなら", "ごめんなさい"], answer: "こんにちは", note: "声調は nǐ が3声、hǎo も3声です。" },
    { lesson: 1, type: "Speaking", title: "音読", hanzi: "我每天学习汉语。", pinyin: "wǒ měitiān xuéxí Hànyǔ.", prompt: "音声のあとに読んでください。", choices: ["読めた", "声調が不安", "意味を確認", "あとで復習"], answer: "読めた", note: "每天 は「毎日」。習慣を表す表現です。" },

    { lesson: 2, type: "Vocabulary", title: "単語", hanzi: "名字", pinyin: "míngzi", prompt: "意味を選んでください。", choices: ["名前", "国籍", "仕事", "住所"], answer: "名前", note: "你叫什么名字？で名前を聞けます。" },
    { lesson: 2, type: "Vocabulary", title: "単語", hanzi: "学生", pinyin: "xuésheng", prompt: "意味を選んでください。", choices: ["学生", "先生", "会社員", "友達"], answer: "学生", note: "生 は軽声で読まれることが多いです。" },
    { lesson: 2, type: "Grammar", title: "是", hanzi: "我是学生。", pinyin: "wǒ shì xuésheng.", prompt: "正しい意味を選んでください。", choices: ["私は学生です", "私は先生ではありません", "あなたは学生ですか", "彼は学生でした"], answer: "私は学生です", note: "A 是 B は「AはBです」。名詞述語文の基本です。" },
    { lesson: 2, type: "Listening", title: "聞き取り", hanzi: "我叫田中。", pinyin: "wǒ jiào Tiánzhōng.", prompt: "何を言っていますか。", choices: ["私は田中といいます", "私は田中を呼びます", "田中さんは学生です", "田中さんは来ます"], answer: "私は田中といいます", note: "叫 は名前を言うときにも使います。" },
    { lesson: 2, type: "Speaking", title: "音読", hanzi: "我不是老师。", pinyin: "wǒ bú shì lǎoshī.", prompt: "音声のあとに読んでください。", choices: ["読めた", "不の声調が不安", "意味を確認", "あとで復習"], answer: "読めた", note: "不 は4声の前で bú に変調します。" },

    { lesson: 3, type: "Vocabulary", title: "単語", hanzi: "什么", pinyin: "shénme", prompt: "意味を選んでください。", choices: ["何", "誰", "いつ", "どこ"], answer: "何", note: "疑問詞は文中の尋ねたい位置に置きます。" },
    { lesson: 3, type: "Vocabulary", title: "単語", hanzi: "喜欢", pinyin: "xǐhuan", prompt: "意味を選んでください。", choices: ["好きである", "分かる", "必要である", "忙しい"], answer: "好きである", note: "欢 は軽声で読まれやすいです。" },
    { lesson: 3, type: "Grammar", title: "吗疑問文", hanzi: "你喜欢中国菜吗？", pinyin: "nǐ xǐhuan Zhōngguó cài ma?", prompt: "正しい意味を選んでください。", choices: ["中国料理が好きですか", "何の料理が好きですか", "中国料理を作れますか", "中国料理を食べましたか"], answer: "中国料理が好きですか", note: "平叙文の末尾に 吗 を置くと Yes/No 疑問文になります。" },
    { lesson: 3, type: "Listening", title: "聞き取り", hanzi: "这是什么？", pinyin: "zhè shì shénme?", prompt: "意味を選んでください。", choices: ["これは何ですか", "これは誰ですか", "これはいくらですか", "これはどこですか"], answer: "これは何ですか", note: "这 は「これ」。那 は「あれ、それ」。" },
    { lesson: 3, type: "Speaking", title: "音読", hanzi: "你叫什么名字？", pinyin: "nǐ jiào shénme míngzi?", prompt: "音声のあとに読んでください。", choices: ["読めた", "疑問詞が不安", "意味を確認", "あとで復習"], answer: "読めた", note: "直訳は「あなたは何という名前ですか」。" },

    { lesson: 4, type: "Vocabulary", title: "単語", hanzi: "没有", pinyin: "méiyǒu", prompt: "意味を選んでください。", choices: ["ない・持っていない", "好きではない", "行かない", "できない"], answer: "ない・持っていない", note: "有 の否定は 不有 ではなく 没有 です。" },
    { lesson: 4, type: "Vocabulary", title: "単語", hanzi: "知道", pinyin: "zhīdào", prompt: "意味を選んでください。", choices: ["知っている", "探している", "始める", "終わる"], answer: "知っている", note: "不知道 で「知りません」。" },
    { lesson: 4, type: "Grammar", title: "不と没", hanzi: "我不去。", pinyin: "wǒ bú qù.", prompt: "正しい意味を選んでください。", choices: ["私は行きません", "私は行きませんでした", "私は持っていません", "私は行けません"], answer: "私は行きません", note: "不 は意志・習慣・判断の否定に使います。" },
    { lesson: 4, type: "Listening", title: "聞き取り", hanzi: "我没有时间。", pinyin: "wǒ méiyǒu shíjiān.", prompt: "意味を選んでください。", choices: ["私は時間がありません", "私は時間を知りません", "私は時間に行きます", "私は時間が好きです"], answer: "私は時間がありません", note: "時間がある は 有时间。" },
    { lesson: 4, type: "Speaking", title: "音読", hanzi: "我不知道。", pinyin: "wǒ bù zhīdào.", prompt: "音声のあとに読んでください。", choices: ["読めた", "声調が不安", "意味を確認", "あとで復習"], answer: "読めた", note: "日常会話で非常によく使います。" },

    { lesson: 5, type: "Vocabulary", title: "単語", hanzi: "家", pinyin: "jiā", prompt: "意味を選んでください。", choices: ["家", "学校", "会社", "駅"], answer: "家", note: "我家 で「私の家」。" },
    { lesson: 5, type: "Vocabulary", title: "単語", hanzi: "朋友", pinyin: "péngyou", prompt: "意味を選んでください。", choices: ["友達", "兄", "先生", "同僚"], answer: "友達", note: "友 は軽声で読まれやすいです。" },
    { lesson: 5, type: "Grammar", title: "的", hanzi: "这是我的书。", pinyin: "zhè shì wǒ de shū.", prompt: "正しい意味を選んでください。", choices: ["これは私の本です", "私はこの本を読みます", "これは私が書いた本です", "私の本はここにあります"], answer: "これは私の本です", note: "所有を表す 的 は日本語の「の」に近いです。" },
    { lesson: 5, type: "Listening", title: "聞き取り", hanzi: "他是我的朋友。", pinyin: "tā shì wǒ de péngyou.", prompt: "意味を選んでください。", choices: ["彼は私の友達です", "彼は私の先生です", "彼は友達がいます", "私は彼の友達です"], answer: "彼は私の友達です", note: "他 は「彼」。她 は「彼女」。発音は同じ tā。" },
    { lesson: 5, type: "Speaking", title: "音読", hanzi: "我家有四口人。", pinyin: "wǒ jiā yǒu sì kǒu rén.", prompt: "音声のあとに読んでください。", choices: ["読めた", "量詞が不安", "意味を確認", "あとで復習"], answer: "読めた", note: "家族の人数には 口 を使います。" },

    { lesson: 6, type: "Vocabulary", title: "単語", hanzi: "今天", pinyin: "jīntiān", prompt: "意味を選んでください。", choices: ["今日", "明日", "昨日", "毎日"], answer: "今日", note: "明天 は明日、昨天 は昨日です。" },
    { lesson: 6, type: "Vocabulary", title: "単語", hanzi: "星期", pinyin: "xīngqī", prompt: "意味を選んでください。", choices: ["曜日・週", "月", "時間", "朝"], answer: "曜日・週", note: "星期一 は月曜日です。" },
    { lesson: 6, type: "Grammar", title: "時間語の位置", hanzi: "我明天去学校。", pinyin: "wǒ míngtiān qù xuéxiào.", prompt: "正しい意味を選んでください。", choices: ["私は明日学校へ行きます", "私は学校で明日勉強します", "明日学校は休みです", "私は毎日学校へ行きます"], answer: "私は明日学校へ行きます", note: "時間語は主語の前後に置けます。" },
    { lesson: 6, type: "Listening", title: "聞き取り", hanzi: "现在几点？", pinyin: "xiànzài jǐ diǎn?", prompt: "意味を選んでください。", choices: ["今何時ですか", "今日は何曜日ですか", "今どこですか", "何分かかりますか"], answer: "今何時ですか", note: "几点 は時刻を尋ねます。" },
    { lesson: 6, type: "Speaking", title: "音読", hanzi: "今天星期六。", pinyin: "jīntiān xīngqīliù.", prompt: "音声のあとに読んでください。", choices: ["読めた", "曜日が不安", "意味を確認", "あとで復習"], answer: "読めた", note: "星期六 は土曜日です。" },

    { lesson: 7, type: "Vocabulary", title: "単語", hanzi: "学校", pinyin: "xuéxiào", prompt: "意味を選んでください。", choices: ["学校", "病院", "店", "駅"], answer: "学校", note: "去学校 で「学校へ行く」。" },
    { lesson: 7, type: "Vocabulary", title: "単語", hanzi: "公司", pinyin: "gōngsī", prompt: "意味を選んでください。", choices: ["会社", "公園", "銀行", "図書館"], answer: "会社", note: "上班 は出勤するという意味です。" },
    { lesson: 7, type: "Grammar", title: "在", hanzi: "我在东京。", pinyin: "wǒ zài Dōngjīng.", prompt: "正しい意味を選んでください。", choices: ["私は東京にいます", "私は東京へ行きます", "私は東京から来ました", "私は東京が好きです"], answer: "私は東京にいます", note: "在 + 場所 で存在場所を表します。" },
    { lesson: 7, type: "Listening", title: "聞き取り", hanzi: "你去哪儿？", pinyin: "nǐ qù nǎr?", prompt: "意味を選んでください。", choices: ["どこへ行きますか", "どこにいますか", "どこから来ましたか", "何をしますか"], answer: "どこへ行きますか", note: "哪儿 は「どこ」。" },
    { lesson: 7, type: "Speaking", title: "音読", hanzi: "我去图书馆。", pinyin: "wǒ qù túshūguǎn.", prompt: "音声のあとに読んでください。", choices: ["読めた", "発音が不安", "意味を確認", "あとで復習"], answer: "読めた", note: "图书馆 は図書館です。" },

    { lesson: 8, type: "Vocabulary", title: "単語", hanzi: "多少", pinyin: "duōshao", prompt: "意味を選んでください。", choices: ["いくら・どれくらい", "なぜ", "どうやって", "どこ"], answer: "いくら・どれくらい", note: "値段や数量を尋ねます。" },
    { lesson: 8, type: "Vocabulary", title: "単語", hanzi: "块", pinyin: "kuài", prompt: "意味を選んでください。", choices: ["元", "個", "冊", "杯"], answer: "元", note: "口語で人民元の単位として使います。" },
    { lesson: 8, type: "Grammar", title: "量詞", hanzi: "一杯咖啡", pinyin: "yì bēi kāfēi", prompt: "正しい意味を選んでください。", choices: ["コーヒー1杯", "コーヒー1冊", "コーヒー1人", "コーヒー1枚"], answer: "コーヒー1杯", note: "飲み物には量詞 杯 をよく使います。" },
    { lesson: 8, type: "Listening", title: "聞き取り", hanzi: "这个多少钱？", pinyin: "zhège duōshao qián?", prompt: "意味を選んでください。", choices: ["これはいくらですか", "これは何ですか", "これはどこですか", "これは誰のですか"], answer: "これはいくらですか", note: "钱 はお金。多少钱 で値段を聞きます。" },
    { lesson: 8, type: "Speaking", title: "音読", hanzi: "我要一杯茶。", pinyin: "wǒ yào yì bēi chá.", prompt: "音声のあとに読んでください。", choices: ["読めた", "量詞が不安", "意味を確認", "あとで復習"], answer: "読めた", note: "我要 は注文でよく使えます。" },

    { lesson: 9, type: "Vocabulary", title: "単語", hanzi: "去过", pinyin: "qùguo", prompt: "意味を選んでください。", choices: ["行ったことがある", "行っている", "行きたい", "行ける"], answer: "行ったことがある", note: "動詞 + 过 で経験を表します。" },
    { lesson: 9, type: "Vocabulary", title: "単語", hanzi: "以前", pinyin: "yǐqián", prompt: "意味を選んでください。", choices: ["以前", "以後", "今", "最近"], answer: "以前", note: "以前 は過去の時点を表します。" },
    { lesson: 9, type: "Grammar", title: "経験の过", hanzi: "我去过北京。", pinyin: "wǒ qùguo Běijīng.", prompt: "正しい意味を選んでください。", choices: ["私は北京へ行ったことがあります", "私は北京へ行っています", "私は北京へ行きたいです", "私は北京へ行きません"], answer: "私は北京へ行ったことがあります", note: "过 は経験、了 は完了・変化に寄ります。" },
    { lesson: 9, type: "Listening", title: "聞き取り", hanzi: "你吃过北京烤鸭吗？", pinyin: "nǐ chīguo Běijīng kǎoyā ma?", prompt: "意味を選んでください。", choices: ["北京ダックを食べたことがありますか", "北京ダックを食べていますか", "北京ダックを食べたいですか", "北京ダックを作れますか"], answer: "北京ダックを食べたことがありますか", note: "吃过 は「食べたことがある」。" },
    { lesson: 9, type: "Speaking", title: "音読", hanzi: "我没去过上海。", pinyin: "wǒ méi qùguo Shànghǎi.", prompt: "音声のあとに読んでください。", choices: ["読めた", "否定形が不安", "意味を確認", "あとで復習"], answer: "読めた", note: "経験の否定は 没 + 動詞 + 过。" },

    { lesson: 10, type: "Vocabulary", title: "単語", hanzi: "买", pinyin: "mǎi", prompt: "意味を選んでください。", choices: ["買う", "売る", "待つ", "持つ"], answer: "買う", note: "卖 mài は「売る」。声調差に注意。" },
    { lesson: 10, type: "Vocabulary", title: "単語", hanzi: "已经", pinyin: "yǐjīng", prompt: "意味を選んでください。", choices: ["すでに", "まだ", "すぐに", "たぶん"], answer: "すでに", note: "已经...了 の形でよく使います。" },
    { lesson: 10, type: "Grammar", title: "了", hanzi: "我买了词典。", pinyin: "wǒ mǎi le cídiǎn.", prompt: "正しい意味を選んでください。", choices: ["私は辞書を買いました", "私は辞書を買います", "私は辞書を買ったことがあります", "私は辞書を買いません"], answer: "私は辞書を買いました", note: "動詞の後の 了 は動作の実現・完了を表します。" },
    { lesson: 10, type: "Listening", title: "聞き取り", hanzi: "他已经回家了。", pinyin: "tā yǐjīng huí jiā le.", prompt: "意味を選んでください。", choices: ["彼はもう家に帰りました", "彼はまだ家にいません", "彼は家に帰りたいです", "彼は家で勉強します"], answer: "彼はもう家に帰りました", note: "文末の 了 は状況の変化も表します。" },
    { lesson: 10, type: "Speaking", title: "音読", hanzi: "我做完作业了。", pinyin: "wǒ zuòwán zuòyè le.", prompt: "音声のあとに読んでください。", choices: ["読めた", "完が不安", "意味を確認", "あとで復習"], answer: "読めた", note: "做完 は「やり終える」。結果補語の入口です。" },

    { lesson: 11, type: "Vocabulary", title: "単語", hanzi: "正在", pinyin: "zhèngzài", prompt: "意味を選んでください。", choices: ["ちょうどしているところ", "すでに", "たぶん", "必ず"], answer: "ちょうどしているところ", note: "在 より進行中の感じが強くなります。" },
    { lesson: 11, type: "Vocabulary", title: "単語", hanzi: "看书", pinyin: "kàn shū", prompt: "意味を選んでください。", choices: ["本を読む", "手紙を書く", "映画を見る", "新聞を買う"], answer: "本を読む", note: "看 は「見る・読む」。目的語で意味が変わります。" },
    { lesson: 11, type: "Grammar", title: "進行", hanzi: "我正在看书。", pinyin: "wǒ zhèngzài kàn shū.", prompt: "正しい意味を選んでください。", choices: ["私はちょうど本を読んでいます", "私は本を読み終えました", "私は本を読んだことがあります", "私は本を読みたいです"], answer: "私はちょうど本を読んでいます", note: "正在 + 動詞 で進行中の動作を表します。" },
    { lesson: 11, type: "Listening", title: "聞き取り", hanzi: "妈妈在做饭。", pinyin: "māma zài zuò fàn.", prompt: "意味を選んでください。", choices: ["母は料理をしています", "母はご飯を食べました", "母は仕事をしています", "母は買い物に行きます"], answer: "母は料理をしています", note: "做饭 は料理する。" },
    { lesson: 11, type: "Speaking", title: "音読", hanzi: "他们正在开会。", pinyin: "tāmen zhèngzài kāi huì.", prompt: "音声のあとに読んでください。", choices: ["読めた", "正在が不安", "意味を確認", "あとで復習"], answer: "読めた", note: "开会 は会議をする。" },

    { lesson: 12, type: "Vocabulary", title: "単語", hanzi: "比", pinyin: "bǐ", prompt: "意味を選んでください。", choices: ["より", "と一緒に", "から", "へ"], answer: "より", note: "比較文の中心になる前置詞です。" },
    { lesson: 12, type: "Vocabulary", title: "単語", hanzi: "高", pinyin: "gāo", prompt: "意味を選んでください。", choices: ["高い", "低い", "速い", "遠い"], answer: "高い", note: "身長や高さに使います。" },
    { lesson: 12, type: "Grammar", title: "比較文", hanzi: "他比我高。", pinyin: "tā bǐ wǒ gāo.", prompt: "正しい意味を選んでください。", choices: ["彼は私より背が高い", "私は彼より背が高い", "彼と私は同じくらい高い", "彼は私ほど高くない"], answer: "彼は私より背が高い", note: "A 比 B + 形容詞 で「AはBより...」。" },
    { lesson: 12, type: "Listening", title: "聞き取り", hanzi: "今天比昨天热。", pinyin: "jīntiān bǐ zuótiān rè.", prompt: "意味を選んでください。", choices: ["今日は昨日より暑い", "昨日は今日より暑い", "今日は昨日ほど暑くない", "今日はとても寒い"], answer: "今日は昨日より暑い", note: "热 は暑い。冷 は寒い・冷たい。" },
    { lesson: 12, type: "Speaking", title: "音読", hanzi: "中文比日文难。", pinyin: "Zhōngwén bǐ Rìwén nán.", prompt: "音声のあとに読んでください。", choices: ["読めた", "比較が不安", "意味を確認", "あとで復習"], answer: "読めた", note: "难 は難しい。容易 は易しい。" },

    { lesson: 13, type: "Vocabulary", title: "単語", hanzi: "会", pinyin: "huì", prompt: "意味を選んでください。", choices: ["習得してできる", "持っている", "行く", "見る"], answer: "習得してできる", note: "会 は学習・訓練で身についた能力に使います。" },
    { lesson: 13, type: "Vocabulary", title: "単語", hanzi: "可以", pinyin: "kěyǐ", prompt: "意味を選んでください。", choices: ["してもよい", "しなければならない", "したことがある", "したばかり"], answer: "してもよい", note: "許可や条件上の可能を表します。" },
    { lesson: 13, type: "Grammar", title: "能・会・可以", hanzi: "我会说一点儿中文。", pinyin: "wǒ huì shuō yìdiǎnr Zhōngwén.", prompt: "正しい意味を選んでください。", choices: ["私は少し中国語を話せます", "私は少し中国語を聞きます", "私は中国語を話してもよいですか", "私は中国語を話したことがあります"], answer: "私は少し中国語を話せます", note: "会说 は習得した結果、話せるという意味です。" },
    { lesson: 13, type: "Listening", title: "聞き取り", hanzi: "这里可以拍照吗？", pinyin: "zhèlǐ kěyǐ pāizhào ma?", prompt: "意味を選んでください。", choices: ["ここで写真を撮ってもいいですか", "ここで写真を撮りましたか", "ここに写真がありますか", "ここは写真館ですか"], answer: "ここで写真を撮ってもいいですか", note: "拍照 は写真を撮る。" },
    { lesson: 13, type: "Speaking", title: "音読", hanzi: "我今天不能去。", pinyin: "wǒ jīntiān bù néng qù.", prompt: "音声のあとに読んでください。", choices: ["読めた", "能が不安", "意味を確認", "あとで復習"], answer: "読めた", note: "不能 は状況的にできない・行けない。" },

    { lesson: 14, type: "Vocabulary", title: "単語", hanzi: "听懂", pinyin: "tīngdǒng", prompt: "意味を選んでください。", choices: ["聞いて理解する", "聞き始める", "聞き逃す", "聞き返す"], answer: "聞いて理解する", note: "懂 は理解するという結果を表します。" },
    { lesson: 14, type: "Vocabulary", title: "単語", hanzi: "找到", pinyin: "zhǎodào", prompt: "意味を選んでください。", choices: ["探し当てる", "探している", "なくす", "持ってくる"], answer: "探し当てる", note: "到 は到達・達成の結果を表します。" },
    { lesson: 14, type: "Grammar", title: "結果補語", hanzi: "我听懂了。", pinyin: "wǒ tīngdǒng le.", prompt: "正しい意味を選んでください。", choices: ["聞いて分かりました", "聞いています", "聞いたことがあります", "聞きたいです"], answer: "聞いて分かりました", note: "動詞 + 結果補語で動作の結果まで表します。" },
    { lesson: 14, type: "Listening", title: "聞き取り", hanzi: "你看完了吗？", pinyin: "nǐ kànwán le ma?", prompt: "意味を選んでください。", choices: ["読み終わりましたか", "読んでいますか", "読んだことがありますか", "読みたいですか"], answer: "読み終わりましたか", note: "看完 は読み終える・見終える。" },
    { lesson: 14, type: "Speaking", title: "音読", hanzi: "我找到了手机。", pinyin: "wǒ zhǎodào le shǒujī.", prompt: "音声のあとに読んでください。", choices: ["読めた", "結果補語が不安", "意味を確認", "あとで復習"], answer: "読めた", note: "手机 は携帯電話です。" },

    { lesson: 15, type: "Vocabulary", title: "単語", hanzi: "进来", pinyin: "jìnlai", prompt: "意味を選んでください。", choices: ["入ってくる", "出ていく", "持っていく", "帰ってくる"], answer: "入ってくる", note: "来 は話し手側へ向かう方向を表します。" },
    { lesson: 15, type: "Vocabulary", title: "単語", hanzi: "回去", pinyin: "huíqu", prompt: "意味を選んでください。", choices: ["帰っていく", "帰ってくる", "入ってくる", "上がってくる"], answer: "帰っていく", note: "去 は話し手から離れる方向です。" },
    { lesson: 15, type: "Grammar", title: "方向補語", hanzi: "他跑出去了。", pinyin: "tā pǎo chūqu le.", prompt: "正しい意味を選んでください。", choices: ["彼は走って出て行きました", "彼は走って入ってきました", "彼は走り終えました", "彼は走れませんでした"], answer: "彼は走って出て行きました", note: "出去 は外へ出ていく方向を表します。" },
    { lesson: 15, type: "Listening", title: "聞き取り", hanzi: "请进来。", pinyin: "qǐng jìnlai.", prompt: "意味を選んでください。", choices: ["入ってきてください", "出て行ってください", "戻ってください", "待ってください"], answer: "入ってきてください", note: "请 は丁寧な依頼を作ります。" },
    { lesson: 15, type: "Speaking", title: "音読", hanzi: "我把书拿过来。", pinyin: "wǒ bǎ shū ná guolai.", prompt: "音声のあとに読んでください。", choices: ["読めた", "方向補語が不安", "意味を確認", "あとで復習"], answer: "読めた", note: "拿过来 は持ってくる。" },

    { lesson: 16, type: "Vocabulary", title: "単語", hanzi: "把", pinyin: "bǎ", prompt: "意味を選んでください。", choices: ["処置対象を前に出す語", "比較を表す語", "経験を表す語", "疑問を表す語"], answer: "処置対象を前に出す語", note: "把構文は目的語への処置結果を言う形です。" },
    { lesson: 16, type: "Vocabulary", title: "単語", hanzi: "放", pinyin: "fàng", prompt: "意味を選んでください。", choices: ["置く", "読む", "洗う", "借りる"], answer: "置く", note: "放在桌子上 で机の上に置く。" },
    { lesson: 16, type: "Grammar", title: "把構文", hanzi: "请把书放在桌子上。", pinyin: "qǐng bǎ shū fàng zài zhuōzi shang.", prompt: "正しい意味を選んでください。", choices: ["本を机の上に置いてください", "机の上の本を読んでください", "本は机の上にあります", "机を本の上に置いてください"], answer: "本を机の上に置いてください", note: "把 + 目的語 + 動詞 + 結果/場所 の形です。" },
    { lesson: 16, type: "Listening", title: "聞き取り", hanzi: "我把作业做完了。", pinyin: "wǒ bǎ zuòyè zuòwán le.", prompt: "意味を選んでください。", choices: ["宿題をやり終えました", "宿題をしています", "宿題を忘れました", "宿題をしたことがあります"], answer: "宿題をやり終えました", note: "把構文は結果補語と相性が良いです。" },
    { lesson: 16, type: "Speaking", title: "音読", hanzi: "请把门关上。", pinyin: "qǐng bǎ mén guānshang.", prompt: "音声のあとに読んでください。", choices: ["読めた", "把構文が不安", "意味を確認", "あとで復習"], answer: "読めた", note: "关上 は閉める。上 は結果補語です。" },

    { lesson: 17, type: "Vocabulary", title: "単語", hanzi: "因为", pinyin: "yīnwèi", prompt: "意味を選んでください。", choices: ["なぜなら", "しかし", "それで", "もし"], answer: "なぜなら", note: "因为...所以... で因果関係を表します。" },
    { lesson: 17, type: "Vocabulary", title: "単語", hanzi: "所以", pinyin: "suǒyǐ", prompt: "意味を選んでください。", choices: ["だから", "または", "しかし", "たとえば"], answer: "だから", note: "原因を受けて結果を導きます。" },
    { lesson: 17, type: "Grammar", title: "因果", hanzi: "因为下雨，所以我不去。", pinyin: "yīnwèi xià yǔ, suǒyǐ wǒ bú qù.", prompt: "正しい意味を選んでください。", choices: ["雨が降っているので、私は行きません", "雨が降っていても、私は行きます", "雨が降る前に、私は行きます", "雨が降ったら、私は行けます"], answer: "雨が降っているので、私は行きません", note: "中国語では 因为 と 所以 を両方使えます。" },
    { lesson: 17, type: "Listening", title: "聞き取り", hanzi: "他今天很忙，不能来。", pinyin: "tā jīntiān hěn máng, bù néng lái.", prompt: "内容として正しいものを選んでください。", choices: ["彼は忙しくて来られない", "彼は暇なので来る", "彼は昨日来た", "彼は忙しくなかった"], answer: "彼は忙しくて来られない", note: "不能来 は来ることができない。" },
    { lesson: 17, type: "Speaking", title: "音読", hanzi: "因为我有事，所以先走了。", pinyin: "yīnwèi wǒ yǒu shì, suǒyǐ xiān zǒu le.", prompt: "音声のあとに読んでください。", choices: ["読めた", "因果が不安", "意味を確認", "あとで復習"], answer: "読めた", note: "有事 は用事がある。" },

    { lesson: 18, type: "Vocabulary", title: "単語", hanzi: "应该", pinyin: "yīnggāi", prompt: "意味を選んでください。", choices: ["すべきだ", "できる", "したことがある", "したばかり"], answer: "すべきだ", note: "助動詞として使います。" },
    { lesson: 18, type: "Vocabulary", title: "単語", hanzi: "准备", pinyin: "zhǔnbèi", prompt: "意味を選んでください。", choices: ["準備する", "説明する", "練習する", "紹介する"], answer: "準備する", note: "准备考试 で試験を準備する。" },
    { lesson: 18, type: "Grammar", title: "日文中訳", hanzi: "毎日中国語を勉強しなければなりません。", pinyin: "", prompt: "もっとも自然な中国語を選んでください。", choices: ["我每天都要学习汉语。", "我每天都学习要汉语。", "每天我汉语要学习。", "我都每天汉语学习要。"], answer: "我每天都要学习汉语。", note: "要 は必要・義務を表せます。每天都 もよく使います。" },
    { lesson: 18, type: "Listening", title: "聞き取り", hanzi: "你应该多练习发音。", pinyin: "nǐ yīnggāi duō liànxí fāyīn.", prompt: "意味を選んでください。", choices: ["もっと発音を練習すべきです", "もっと漢字を書くべきです", "もっと早く話せます", "発音を聞いたことがあります"], answer: "もっと発音を練習すべきです", note: "多 + 動詞 で「もっと...する」。" },
    { lesson: 18, type: "Speaking", title: "音読", hanzi: "我正在准备考试。", pinyin: "wǒ zhèngzài zhǔnbèi kǎoshì.", prompt: "音声のあとに読んでください。", choices: ["読めた", "準備が不安", "意味を確認", "あとで復習"], answer: "読めた", note: "考试 は試験です。" },

    { lesson: 19, type: "Vocabulary", title: "単語", hanzi: "虽然", pinyin: "suīrán", prompt: "意味を選んでください。", choices: ["...ではあるが", "もし", "それとも", "なぜなら"], answer: "...ではあるが", note: "虽然...但是... で逆接を作ります。" },
    { lesson: 19, type: "Vocabulary", title: "単語", hanzi: "但是", pinyin: "dànshì", prompt: "意味を選んでください。", choices: ["しかし", "だから", "そして", "もし"], answer: "しかし", note: "可是 も「しかし」です。" },
    { lesson: 19, type: "Grammar", title: "逆接", hanzi: "虽然很难，但是很有意思。", pinyin: "suīrán hěn nán, dànshì hěn yǒu yìsi.", prompt: "正しい意味を選んでください。", choices: ["難しいけれど、とても面白い", "難しいので、面白くない", "簡単だけれど、面白い", "面白いので、難しくない"], answer: "難しいけれど、とても面白い", note: "中国語では 虽然 と 但是 を両方使えます。" },
    { lesson: 19, type: "Listening", title: "聞き取り", hanzi: "这个问题不太难。", pinyin: "zhège wèntí bú tài nán.", prompt: "意味を選んでください。", choices: ["この問題はあまり難しくない", "この問題はとても難しい", "この問題は簡単すぎる", "この問題は多すぎる"], answer: "この問題はあまり難しくない", note: "不太 は「あまり...ではない」。" },
    { lesson: 19, type: "Speaking", title: "音読", hanzi: "虽然我很忙，但是每天学习。", pinyin: "suīrán wǒ hěn máng, dànshì měitiān xuéxí.", prompt: "音声のあとに読んでください。", choices: ["読めた", "逆接が不安", "意味を確認", "あとで復習"], answer: "読めた", note: "検定作文でも使いやすい型です。" },

    { lesson: 20, type: "Vocabulary", title: "単語", hanzi: "复习", pinyin: "fùxí", prompt: "意味を選んでください。", choices: ["復習する", "予習する", "練習する", "説明する"], answer: "復習する", note: "预习 は予習する。" },
    { lesson: 20, type: "Vocabulary", title: "単語", hanzi: "提高", pinyin: "tígāo", prompt: "意味を選んでください。", choices: ["高める・向上させる", "下げる", "比べる", "終える"], answer: "高める・向上させる", note: "提高水平 でレベルを上げる。" },
    { lesson: 20, type: "Grammar", title: "総合", hanzi: "只要每天复习，就能提高听力。", pinyin: "zhǐyào měitiān fùxí, jiù néng tígāo tīnglì.", prompt: "正しい意味を選んでください。", choices: ["毎日復習しさえすれば、リスニング力を高められる", "毎日復習しても、リスニング力は上がらない", "毎日聞けば、復習しなくてよい", "復習したことがあるので、聞けない"], answer: "毎日復習しさえすれば、リスニング力を高められる", note: "只要...就... は「...しさえすれば...」。" },
    { lesson: 20, type: "Listening", title: "聞き取り", hanzi: "明天的考试你准备好了吗？", pinyin: "míngtiān de kǎoshì nǐ zhǔnbèi hǎo le ma?", prompt: "意味を選んでください。", choices: ["明日の試験の準備はできましたか", "明日の試験は難しいですか", "明日の試験は何時ですか", "明日の試験を受けましたか"], answer: "明日の試験の準備はできましたか", note: "准备好 は準備ができる。" },
    { lesson: 20, type: "Speaking", title: "音読", hanzi: "我想通过中国语检定三级。", pinyin: "wǒ xiǎng tōngguò Zhōngguóyǔ jiǎndìng sānjí.", prompt: "音声のあとに読んでください。", choices: ["読めた", "検定語彙が不安", "意味を確認", "あとで復習"], answer: "読めた", note: "通过考试 は試験に合格する。" },
  ],
};
